socialmedia/posts/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', home, name='home1'),
    path('posts/<str:page>/', index, name='home'),
    path('upload_post/', AddPostView.as_view(), name='upload_post'),
]

socialmedia/profiles/urls.py
# profiles/urls.py
from django.urls import path
from .views import ProfileDetailView, ProfileCreateView, ProfileUpdateView

# app_name = 'profiles'

urlpatterns = [
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name='profile'),
    path('profile/create/', ProfileCreateView.as_view(), name='profile_create'),
    path('profile/update/<int:pk>/', ProfileUpdateView.as_view(), name='profile_update'),
]

socialmedia/social/urls.py
from django.urls import path
from .views import SendFriendRequestView, AcceptFriendRequestView, FollowUserView, UnfollowUserView

app_name = 'social'

urlpatterns = [
    path('send_friend_request/<int:user_id>/', SendFriendRequestView.as_view(), name='send_friend_request'),
    path('accept_friend_request/<int:pk>/', AcceptFriendRequestView.as_view(), name='accept_friend_request'),
    path('follow_user/', FollowUserView.as_view(), name='follow_user'),
    path('unfollow_user/<int:pk>/', UnfollowUserView.as_view(), name='unfollow_user'),
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from posts import views as post_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('profiles/', include('profiles.urls')),
    path('social/', include('social.urls')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialmedia/profiles/models.py
from django.db import models
from authentication.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True, max_length=500)
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    cover_photo = models.ImageField(upload_to='cover_photos/', blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    social_links = models.JSONField(default=dict, blank=True)

socialmedia/profiles/forms.py
# profiles/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'profile_pic', 'cover_photo', 'phone_number', 'address', 'social_links']

socialmedia/profiles/views.py
# profiles/views.py
from django.views.generic import DetailView, CreateView, UpdateView
from .models import Profile
from .forms import ProfileForm
from social.models import Friendship  # Đảm bảo rằng bạn đã import model Friendship

class ProfileDetailView(DetailView):
    model = Profile
    template_name = 'profiles/profile_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Lấy đối tượng Friendship dựa trên user hiện tại và user của profile
        # Giả định rằng user1 là người gửi yêu cầu kết bạn và user2 là người nhận
        friendship = Friendship.objects.filter(
        user1=self.request.user, user2=self.object.user
        ).first() or Friendship.objects.filter(
        user1=self.object.user, user2=self.request.user
        ).first()

        context['friendship'] = friendship
        print(friendship)
        return context


class ProfileCreateView(CreateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'profiles/profile_form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class ProfileUpdateView(UpdateView):
    model = Profile
    form_class = ProfileForm
    template_name = 'profiles/profile_form.html'

socialmedia/profiles/templates/profiles/profile_form.html
<!-- profiles/templates/profiles/profile_form.html -->
{% extends "base_generic.html" %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
{% endblock %}

socialmedia/profiles/templates/profiles/xx.html
{% if friendship %}
    <!-- Nút Chấp nhận yêu cầu kết bạn -->
    <form action="{% url 'social:accept_friend_request' pk=friendship_id %}" method="post">
      {% csrf_token %}
      <button type="submit">Accept Friend Request</button>
    </form>
    {% endif %}
    <!-- Nút Theo dõi -->
    {% if friendship %}
    <form action="{% url 'social:follow_user' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="followee" value="{{ object.user.id }}">
      <button type="submit">Follow</button>
    </form>
    <!-- Nút Bỏ theo dõi -->
    <form action="{% url 'social:unfollow_user' pk=follow_id %}" method="post">
      {% csrf_token %}
      <button type="submit">Unfollow</button>
    </form>
    {% endif %}